import type { Metadata } from "next";
import localFont from "next/font/local";
import { Outfit } from 'next/font/google';
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import Navbar from "./components/Navbar";

const inter = Outfit({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <meta
            name="google-site-verification"
            content="LOO0jmi15OL4jhp4fk3UFOpRalTV7Q30ENUhx_Pnakc"
          />
        </head>
        <body className={inter.className}>
          <SignedOut>
            <SignInButton>
              <div className="p-5">
                <button
                  type="button"
                  className="p-2 px-5 bg-blue-500 text-xl text-white rounded-lg "
                >
                  Sign In
                </button>
              </div>
            </SignInButton>
          </SignedOut>
          <SignedIn>
            <Navbar />
            {children}
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
